name: Deploy Flutter Web

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      BASE_HREF: "/supa_chat/"

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Run Deployment
        run: |
          make deploy \
            OUTPUT=supa_chat \
            SUPABASE_URL="${{ secrets.SUPABASE_URL }}" \
            SUPABASE_ANON_KEY="${{ secrets.SUPABASE_ANON_KEY }}"